- name: Build Debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: BluetoothHook-debug
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
          retention-days: 14